blog/urls.py
from django.urls import path,include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

app_name="blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("Contact/", views.contact, name="contact"),
    path("About/", views.about, name="about"),
    path("Blog/<slug:slug>/delete/<int:id>", views.commentaire_delete, name="delete_comment"),
    path("Blog/<slug:slug>/update/<int:id>", views.commentaire_update, name="update_comment"),
    path("Blog/", views.blog, name="blog"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('Auth/', include('Authentification.urls')),
    path('admin/filebrowser/', site.urls),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.text import slugify
from django.utils import timezone


User = get_user_model()

# Create your models here.


class Categorie(models.Model):

    class Meta:
        verbose_name = "Catégorie"
        verbose_name_plural = "Catégories"

    nom = models.CharField(verbose_name="Nom", max_length=255)
    description = models.TextField()

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom
    

class Tag(models.Model):

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    nom = models.CharField(verbose_name="Nom", max_length=255)

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom
    

class Article(models.Model):

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    titre = models.CharField(max_length=256)
    couverture = models.ImageField(upload_to="articles")
    resume = models.TextField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    auteur_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="auteur_article_ids", verbose_name="auteurs")
    categorie_id = models.ForeignKey('blog.Categorie', on_delete=models.SET_NULL, null=True, related_name="categorie_article_ids", verbose_name="Catégories")
    tag_ids = models.ManyToManyField('blog.Tag', related_name="tag_article_ids", verbose_name="Tags")
    
    est_publie = models.BooleanField(default=False)
    date_de_publication = models.DateField(verbose_name="Date de publication", auto_now_add=True)

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

def save(self, *args, **kwargs):
    if not self.date_de_publication:  # If the publication date is not set
        self.date_de_publication = timezone.now().date()  # Set current date
    if not self.slug:
        self.slug = slugify(self.titre)  # Generate a slug from the title
        if Article.objects.filter(slug=self.slug).exists():  # Check if the slug already exists
            self.slug = f"{self.slug}-{self.id}"  # Append the article's ID if the slug is not unique
    super().save(*args, **kwargs)
    
    def __str__(self):
        return self.titre
    
    def nombreDeLike(self):
        return self.likes.count()
    

class Commentaire(models.Model):

    class Meta:
        verbose_name = "Commentaire"
        verbose_name_plural = "Commentaires"

    auteur_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="auteur_commentaire_ids")
    article_id = models.ForeignKey('blog.Article', on_delete=models.CASCADE, related_name="article_commentaire_ids")
    contenu = models.TextField()

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.auteur_id.username


class Like(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)  # L'utilisateur qui like
    article = models.ForeignKey('blog.Article', related_name='likes', on_delete=models.CASCADE)  # L'article liké
    date = models.DateTimeField(auto_now_add=True)  # Date du like

    class Meta:
        verbose_name = "like"
        verbose_name_plural = "likes"
        unique_together = ('utilisateur', 'article')  # Un utilisateur ne peut liker qu'une seule fois un article

    def __str__(self):
        return f"{self.utilisateur.username} a liké {self.article.titre}"

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from blog.models import Article,Commentaire
from django.contrib import messages
from blog.form import InfosGeneralesForm, ContenuForm, StandardsForm, CommentaireForm

# Create your views here.

def index(request):

    articles = Article.objects.filter(est_publie=True)[:3]  # Récupère les articles publiés
  
    datas = {
        "articles" : articles,
    }

    return render(request, 'index.html', datas)

def contact(request):
    datas = {

    }

    return render(request, 'contact.html', datas)



@login_required
def ajout_article(request):
    if request.method == "POST":
        print("Fichiers reçus :", request.FILES)
        form_infos = InfosGeneralesForm(request.POST, request.FILES)
        form_contenu = ContenuForm(request.POST)
        form_standards = StandardsForm(request.POST)

        print(form_infos.is_valid())
        print(form_contenu.is_valid())
        print(form_standards.is_valid())
         

        if form_infos.is_valid() and form_contenu.is_valid() and form_standards.is_valid():
            # Création de l'article sans sauvegarde immédiate
            print("teste")
            article = Article(
                titre=form_infos.cleaned_data['titre'],
                couverture=request.FILES.get('couverture', None),
                categorie_id=form_infos.cleaned_data['categorie_id'],
                contenu=form_contenu.cleaned_data['contenu'],
                est_publie=form_standards.cleaned_data['est_publie'],
                statut=form_standards.cleaned_data['statut'],
                auteur_id=request.user
            )
            article.save()  # Sauvegarde de l'article

            # Gestion des tags
            article.tag_ids.set(form_infos.cleaned_data['tag_ids'])

            messages.success(request, "Article ajouté avec succès !")
            return redirect('blog:board')

        else:
            messages.error(request, "Veuillez corriger les erreurs dans le formulaire.")

    else:
        form_infos = InfosGeneralesForm()
        form_contenu = ContenuForm()
        form_standards = StandardsForm()

    return render(request, 'ajout_article.html', {
        'form_infos': form_infos,
        'form_contenu': form_contenu,
        'form_standards': form_standards
    })

@login_required
def update_article(request, slug):
    # Récupérer l'article existant par son slug
    article = get_object_or_404(Article, slug=slug)

    if request.method == 'POST':
        # Pré-remplir les trois formulaires avec les données existantes de l'article
        form_infos = InfosGeneralesForm(request.POST, request.FILES, instance=article)
        form_contenu = ContenuForm(request.POST, instance=article)
        form_standards = StandardsForm(request.POST, instance=article)

        # Vérifier si tous les formulaires sont valides
        if form_infos.is_valid() and form_contenu.is_valid() and form_standards.is_valid():
            # Sauvegarder les modifications de l'article
            form_infos.save()  # Sauvegarder InfosGeneralesForm
            form_contenu.save()  # Sauvegarder ContenuForm
            form_standards.save()  # Sauvegarder StandardsForm

            # Gestion des tags (si nécessaire)
            article.tag_ids.set(form_infos.cleaned_data['tag_ids'])

            messages.success(request, "Article mis à jour avec succès !")
            return redirect('blog:board')  # Rediriger vers la page des articles
        else:
            messages.error(request, "Veuillez corriger les erreurs dans les formulaires.")
    else:
        # Pré-remplir les formulaires avec les données existantes de l'article lors du GET
        form_infos = InfosGeneralesForm(instance=article)
        form_contenu = ContenuForm(instance=article)
        form_standards = StandardsForm(instance=article)

    return render(request, 'ajout_article.html', {
        'form_infos': form_infos,
        'form_contenu': form_contenu,
        'form_standards': form_standards,
        'article': article,
    })

@login_required
def delete_article(request,slug):

    article = get_object_or_404(Article, slug=slug)
    if article:
        article.delete()
        return redirect('blog:board')

    return render(request, 'dashboard.html')

def about(request):
    datas = {

    }

    return render(request, 'about.html', datas)

def blog(request):

    articles = Article.objects.filter(est_publie=True)  # Récupère les articles publiés
    
    paginator = Paginator(articles, 6) 
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)

    datas = {
        "articles" : articles,
        "page_obj": page_obj
    }

    return render(request, 'blog.html', datas)

def blog_single(request, slug):
    article = get_object_or_404(Article, slug=slug)
    form = CommentaireForm()
    datas = {
        "article" : article,
        "form_comment" : form
    }

    if request.method == "POST":
        form = CommentaireForm(request.POST)
        if form.is_valid():
            Commentaire.objects.create(
                article_id=article,
                auteur_id=request.user,
                contenu=form.cleaned_data["contenu"]
            )
            messages.success(request, "Votre commentaire a été ajouté avec succès !")
            return redirect("blog:article", slug=article.slug)

    return render(request, 'blog-single.html', datas)

@login_required
def commentaire_delete(request, slug, id):

    article = get_object_or_404(Article, slug=slug)
    commentaire = get_object_or_404(Commentaire, id=id, article_id=article)

    commentaire.delete()
    messages.success(request, "Commentaire supprimé avec succès.")

    return redirect("blog:article", slug=article.slug)

@login_required
def commentaire_update(request, slug, id):
    article = get_object_or_404(Article, slug=slug)
    commentaire = get_object_or_404(Commentaire, id=id, article_id=article)
    print(commentaire)

    if request.method == 'POST':
        form_comment = CommentaireForm(request.POST, instance=commentaire)
        if form_comment.is_valid():
            form_comment.save()
            messages.success(request, "Commentaire mis à jour avec succès !")
            return redirect('blog:article', slug=article.slug)  # Redirection vers l'article mis à jour
        else:
            messages.error(request, "Veuillez corriger les erreurs dans le formulaire.")

    else:
        form_comment = CommentaireForm(instance=commentaire)  # Pré-remplir le formulaire avec les données existantes

    return render(request, 'blog-single.html', {
        'form_comment': form_comment,
        'article': article,
        'commentaire': commentaire
    })

def tag_page(request,tag):

    articles = Article.objects.filter(tag=tag)

    paginator = Paginator(articles, 6) 
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)

    datas = {
        "articles" : articles,
        "page_obj": page_obj
    }

    return render()

blog/templates/ajout_article.html
{% extends "base/dashboardbase.html" %}
{% load static %}


{% block content %}

    <div class="container mt-5">
        <div class="card shadow p-4">
            <h2 class="text-center mb-4">Ajout d'un nouvel article</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                

                <fieldset class="border p-4 rounded mb-4">
                    <legend class="fw-semibold fs-5">Informations Générales</legend>
                    {{ form_infos.as_p }}
                </fieldset>

                <fieldset class="border p-4 rounded mb-4">
                    <legend class="fw-semibold fs-5">Contenu de l’Article</legend>
                    {{ form_contenu.as_p }} <!-- CKEditor 5 devrait s'afficher ici -->
                </fieldset>

                <fieldset class="border p-4 rounded mb-4">
                    <legend class="fw-semibold fs-5">Standards</legend>
                    {{ form_standards.as_p }}
                </fieldset>

                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Publier</button>
                </div>
            </form>
        </div>
    </div>

    {% endblock %}

blog/templates/blog-single.html
{% extends "base/base.html" %}
{% load static %}

{% block content%}
    <!-- Page Header Start -->
	<div class="page-header parallaxie">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<!-- Page Header Box Start -->
					<div class="page-header-box">
                        <h1 class="text-anime-style-2" data-cursor="-opaque">{{ article.titre|truncatechars:20 }}</h1>
						<nav class="wow fadeInUp">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="{% url 'blog:index' %}">home</a></li>
								<li class="breadcrumb-item active" aria-current="page">{{article.titre}}</li>
							</ol>
						</nav>
					</div>
					<!-- Page Header Box End -->
				</div>
			</div>
		</div>
	</div>
	<!-- Page Header End -->

    <!-- Page Single Post Start -->
    <div class="page-single-post">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Post Featured Image Start -->
                    <div class="post-image">
                        <figure class="image-anime reveal">
                            <img src="{{article.couverture.url }}" alt="">
                        </figure>
                    </div>
                    <!-- Post Featured Image Start -->

                    <!-- Post Single Content Start -->
                    <div class="post-content">
                        <!-- Post Entry Start -->
                        {{article.contenu|safe }}
                        <!-- Post Entry End -->

                        <!-- Post Tag Links Start -->
                        <div class="post-tag-links">
                            <div class="row align-items-center">
                                <div class="col-lg-8">
                                    <!-- Post Tags Start -->
                                    <div class="post-tags wow fadeInUp" data-wow-delay="0.5s">
                                        <span class="tag-links">
                                            Tags:
                                            {% for tag in article.tag_ids.all  %}
                                            <a href="#">{{tag.nom}}</a>
                                            {% endfor %}
                                        </span>
                                    </div>
                                    <!-- Post Tags End -->
                                </div>

                                <div class="col-lg-4">
                                    <!-- Post Social Links Start -->
                                    <div class="post-social-sharing wow fadeInUp" data-wow-delay="0.5s">
                                        <ul>
                                            <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
                                            <li><a href="#"><i class="fa-brands fa-linkedin-in"></i></a></li>
                                            <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
                                            <li><a href="#"><i class="fa-brands fa-x-twitter"></i></a></li>
                                        </ul>
                                    </div>
                                    <!-- Post Social Links End -->
                                </div>
                            </div>
                        </div>
                        <!-- Post Tag Links End -->
                    </div>
                    <!-- Post Single Content End -->
                </div>
                <!-- Comment Form Start -->
                <div class="comment-form col-lg-12 py-5">
                    <h3>Laisser un commentaire</h3>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form_comment.as_p }}  <!-- Affiche le champ du formulaire avec les styles -->
                        </div>
                        <button type="submit" class="btn btn-primary">Envoyer</button>
                    </form>
                </div>
                <!-- Comment Form End -->

                <!-- Comment Section Start -->
                <div class="post-comments">
                    <h3>Commentaires</h3>
                    {% if article.article_commentaire_ids.exists %}
                        {% for commentaire in article.article_commentaire_ids.all|dictsort:"created_at" %}
                        <div class="comment">
                            <p><strong>{{ commentaire.auteur_id.username }}</strong> - {{ commentaire.created_at|date:"d M Y H:i" }}</p>
                            <p>{{ commentaire.contenu }}</p>
                            {% if request.user == commentaire.auteur_id %}
                                <a href="{% url 'blog:update_comment' article.slug commentaire.id %}" class="btn btn-success">Modifier</a>
                                <a href="{% url 'blog:delete_comment' article.slug commentaire.id %}" class="btn btn-danger">Supprimer</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    {% else %}
                        <p>Aucun commentaire pour l'instant. Soyez le premier à commenter !</p>
                    {% endif %}
                </div>
                <!-- Comment Section End -->

            </div>
        </div>
    </div>
    <!-- Page Single Post End -->




    <!-- Footer Start -->
    <footer class="main-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <!-- Footer Header Start -->
                    <div class="footer-header">
                        <div class="row align-items-center">  
                            <div class="col-md-6">
                                <!-- Footer Logo Start -->
                                <div class="footer-logo">
                                    <img src="{% static 'images/footer-logo.svg' %}" alt="">
                                </div>
                                <!-- Footer Logo End -->
                            </div>

                            <div class="col-md-6">
                                <!-- Footer Social Link Start -->
                                <div class="footer-social-links">
                                    <div class="footer-social-link-title">
                                        <h3>follow our socials</h3>
                                    </div>
                                    <ul>
                                        <li><a href="#"><i class="fa-brands fa-facebook-f"></i></a></li>
                                        <li><a href="#"><i class="fa-brands fa-dribbble"></i></a></li>
                                        <li><a href="#"><i class="fa-brands fa-instagram"></i></a></li>
                                    </ul>
                                </div>
                                <!-- Footer Social Link End -->
                            </div>
                        </div>
                    </div>
                    <!-- Footer Header End -->
                </div>

                <div class="col-lg-3 col-md-6">
                    <!-- Footer Links Start -->
                     <div class="footer-links">
                        <h3>information</h3>
                        <ul>
                            <li><a href="{% url 'blog:about' %}">about our company</a></li>
                            <li><a href="{% url 'blog:index' %}">read our blog</a></li>
                        </ul>
                     </div>
                    <!-- Footer Links End -->
                </div>

                <div class="col-lg-3 col-md-6">
                    <!-- Footer Links Start -->
                     <div class="footer-links">
                        <h3>portfolio</h3>
                        <ul>
                            <li><a href="#">luxury home design</a></li>
                            <li><a href="#">residential interior design</a></li>
                            <li><a href="#">commercial space design</a></li>
                            <li><a href="#">residential interior design</a></li>
                            <li><a href="#">renovation and restoration design</a></li>
                        </ul>
                     </div>
                    <!-- Footer Links End -->
                </div>

                <div class="col-lg-3 col-md-6">
                    <!-- Footer Contact Box Start -->
                    <div class="footer-contact-box footer-links">
                        <h3>contact us</h3>
                        <!-- Footer Contact Item Start -->
                        <div class="footer-contact-item">
                            <div class="icon-box">
                                <i class="fa-solid fa-phone"></i>
                            </div>
                            <div class="footer-contact-content">
                                <p>+1 (213) 465 789</p>
                            </div>
                        </div>
                        <!-- Footer Contact Item End -->

                        <!-- Footer Contact Item Start -->
                        <div class="footer-contact-item">
                            <div class="icon-box">
                                <i class="fa-solid fa-envelope"></i>
                            </div>
                            <div class="footer-contact-content">
                                <p>info@domain.com</p>
                            </div>
                        </div>
                        <!-- Footer Contact Item End -->

                        <!-- Footer Contact Item Start -->
                        <div class="footer-contact-item">
                            <div class="icon-box">
                                <i class="fa-solid fa-location-dot"></i>
                            </div>
                            <div class="footer-contact-content">
                                <p>Generała Ziętka Jerzego 54, Mysłowice 41-412</p>
                            </div>
                        </div>
                        <!-- Footer Contact Item End -->
                    </div>
                    <!-- Footer Contact Box End -->
                </div>

                <div class="col-lg-3 col-md-6">
                    <!-- Footer Newsletter Form Start -->
                    <div class="footer-latest-news footer-links">
                        <h3>get the latest trending news</h3>
                        
                        <div class="footer-newsletter-form">
                            <p>Your Dream Space Starts Here Get Exclusive Design Straight Your Inbox!</p>

                            <form id="newslettersForm" action="#" method="POST">
                                <div class="form-group">
                                    <input type="email" name="email" class="form-control"  id="mail" placeholder="Enter your email" required>
                                    <button type="submit"><i class="fa-solid fa-arrow-right-long"></i> </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- Footer Newsletter Form End -->
                </div>
            </div>

            <!-- Footer Copyright Section Start -->
            <div class="footer-copyright">
                <div class="row">
                    <div class="col-md-12">
                        <!-- Footer Copyright Start -->
                        <div class="footer-copyright-text">
                            <p>Copyright © 2024 All Rights Reserved.</p>
                        </div>
                        <!-- Footer Copyright End -->
                    </div>
                </div>
            </div>
            <!-- Footer Copyright Section End -->
        </div>
    </footer>
    <!-- Footer End -->
    {% endblock %}