Authentification/urls.py
from django.urls import path,include
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from Authentification import views

app_name = "Authentification"

urlpatterns= [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view,name="logout"),
    path('register/', views.register_view, name='register'),
    path('forget-password/', views.forgetpassword, name='forgetpassword'),
    path('forget-password/<str:uidb64>/<str:token>/', views.changepassword, name='changepassword'),
    path('register/<str:uidb64>/<str:token>/', views.active_account, name='activecompte'),
]

blog/urls.py
from django.urls import path,include
from blog import views
from django.conf import settings
from django.conf.urls.static import static

app_name="blog"

urlpatterns = [
    path("", views.index, name="index"),
    path("Contact/", views.contact, name="contact"),
    path("About/", views.about, name="about"),
    path("Blog/<slug:slug>/delete/<int:id>", views.commentaire_delete, name="delete_comment"),
    path("Blog/<slug:slug>/update/<int:id>", views.commentaire_update, name="update_comment"),
    path("Blog/", views.blog, name="blog"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

iit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
    path('Auth/', include('Authentification.urls')),
    path('admin/filebrowser/', site.urls),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.text import slugify
from django.utils import timezone


User = get_user_model()

# Create your models here.


class Categorie(models.Model):

    class Meta:
        verbose_name = "Catégorie"
        verbose_name_plural = "Catégories"

    nom = models.CharField(verbose_name="Nom", max_length=255)
    description = models.TextField()

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom
    

class Tag(models.Model):

    class Meta:
        verbose_name = "Tag"
        verbose_name_plural = "Tags"

    nom = models.CharField(verbose_name="Nom", max_length=255)

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.nom
    

class Article(models.Model):

    class Meta:
        verbose_name = "Article"
        verbose_name_plural = "Articles"

    titre = models.CharField(max_length=256)
    couverture = models.ImageField(upload_to="articles")
    resume = models.TextField()
    slug = models.SlugField(unique=True, blank=True, null=True)
    auteur_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="auteur_article_ids", verbose_name="auteurs")
    categorie_id = models.ForeignKey('blog.Categorie', on_delete=models.SET_NULL, null=True, related_name="categorie_article_ids", verbose_name="Catégories")
    tag_ids = models.ManyToManyField('blog.Tag', related_name="tag_article_ids", verbose_name="Tags")
    
    est_publie = models.BooleanField(default=False)
    date_de_publication = models.DateField(verbose_name="Date de publication", auto_now_add=True)

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

def save(self, *args, **kwargs):
    if not self.date_de_publication:  # If the publication date is not set
        self.date_de_publication = timezone.now().date()  # Set current date
    if not self.slug:
        self.slug = slugify(self.titre)  # Generate a slug from the title
        if Article.objects.filter(slug=self.slug).exists():  # Check if the slug already exists
            self.slug = f"{self.slug}-{self.id}"  # Append the article's ID if the slug is not unique
    super().save(*args, **kwargs)
    
    def __str__(self):
        return self.titre
    
    def nombreDeLike(self):
        return self.likes.count()
    

class Commentaire(models.Model):

    class Meta:
        verbose_name = "Commentaire"
        verbose_name_plural = "Commentaires"

    auteur_id = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="auteur_commentaire_ids")
    article_id = models.ForeignKey('blog.Article', on_delete=models.CASCADE, related_name="article_commentaire_ids")
    contenu = models.TextField()

    # Standards
    statut = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    last_updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.auteur_id.username


class Like(models.Model):
    utilisateur = models.ForeignKey(User, on_delete=models.CASCADE)  # L'utilisateur qui like
    article = models.ForeignKey('blog.Article', related_name='likes', on_delete=models.CASCADE)  # L'article liké
    date = models.DateTimeField(auto_now_add=True)  # Date du like

    class Meta:
        verbose_name = "like"
        verbose_name_plural = "likes"
        unique_together = ('utilisateur', 'article')  # Un utilisateur ne peut liker qu'une seule fois un article

    def __str__(self):
        return f"{self.utilisateur.username} a liké {self.article.titre}"

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from blog.models import Article,Commentaire
from django.contrib import messages
from blog.form import InfosGeneralesForm, ContenuForm, StandardsForm, CommentaireForm

# Create your views here.

def index(request):

    articles = Article.objects.filter(est_publie=True)[:3]  # Récupère les articles publiés
  
    datas = {
        "articles" : articles,
    }

    return render(request, 'index.html', datas)

def contact(request):
    datas = {

    }

    return render(request, 'contact.html', datas)



@login_required
def ajout_article(request):
    if request.method == "POST":
        print("Fichiers reçus :", request.FILES)
        form_infos = InfosGeneralesForm(request.POST, request.FILES)
        form_contenu = ContenuForm(request.POST)
        form_standards = StandardsForm(request.POST)

        print(form_infos.is_valid())
        print(form_contenu.is_valid())
        print(form_standards.is_valid())
         

        if form_infos.is_valid() and form_contenu.is_valid() and form_standards.is_valid():
            # Création de l'article sans sauvegarde immédiate
            print("teste")
            article = Article(
                titre=form_infos.cleaned_data['titre'],
                couverture=request.FILES.get('couverture', None),
                categorie_id=form_infos.cleaned_data['categorie_id'],
                contenu=form_contenu.cleaned_data['contenu'],
                est_publie=form_standards.cleaned_data['est_publie'],
                statut=form_standards.cleaned_data['statut'],
                auteur_id=request.user
            )
            article.save()  # Sauvegarde de l'article

            # Gestion des tags
            article.tag_ids.set(form_infos.cleaned_data['tag_ids'])

            messages.success(request, "Article ajouté avec succès !")
            return redirect('blog:board')

        else:
            messages.error(request, "Veuillez corriger les erreurs dans le formulaire.")

    else:
        form_infos = InfosGeneralesForm()
        form_contenu = ContenuForm()
        form_standards = StandardsForm()

    return render(request, 'ajout_article.html', {
        'form_infos': form_infos,
        'form_contenu': form_contenu,
        'form_standards': form_standards
    })

@login_required
def update_article(request, slug):
    # Récupérer l'article existant par son slug
    article = get_object_or_404(Article, slug=slug)

    if request.method == 'POST':
        # Pré-remplir les trois formulaires avec les données existantes de l'article
        form_infos = InfosGeneralesForm(request.POST, request.FILES, instance=article)
        form_contenu = ContenuForm(request.POST, instance=article)
        form_standards = StandardsForm(request.POST, instance=article)

        # Vérifier si tous les formulaires sont valides
        if form_infos.is_valid() and form_contenu.is_valid() and form_standards.is_valid():
            # Sauvegarder les modifications de l'article
            form_infos.save()  # Sauvegarder InfosGeneralesForm
            form_contenu.save()  # Sauvegarder ContenuForm
            form_standards.save()  # Sauvegarder StandardsForm

            # Gestion des tags (si nécessaire)
            article.tag_ids.set(form_infos.cleaned_data['tag_ids'])

            messages.success(request, "Article mis à jour avec succès !")
            return redirect('blog:board')  # Rediriger vers la page des articles
        else:
            messages.error(request, "Veuillez corriger les erreurs dans les formulaires.")
    else:
        # Pré-remplir les formulaires avec les données existantes de l'article lors du GET
        form_infos = InfosGeneralesForm(instance=article)
        form_contenu = ContenuForm(instance=article)
        form_standards = StandardsForm(instance=article)

    return render(request, 'ajout_article.html', {
        'form_infos': form_infos,
        'form_contenu': form_contenu,
        'form_standards': form_standards,
        'article': article,
    })

@login_required
def delete_article(request,slug):

    article = get_object_or_404(Article, slug=slug)
    if article:
        article.delete()
        return redirect('blog:board')

    return render(request, 'dashboard.html')

def about(request):
    datas = {

    }

    return render(request, 'about.html', datas)

def blog(request):

    articles = Article.objects.filter(est_publie=True)  # Récupère les articles publiés
    
    paginator = Paginator(articles, 6) 
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)

    datas = {
        "articles" : articles,
        "page_obj": page_obj
    }

    return render(request, 'blog.html', datas)

def blog_single(request, slug):
    article = get_object_or_404(Article, slug=slug)
    form = CommentaireForm()
    datas = {
        "article" : article,
        "form_comment" : form
    }

    if request.method == "POST":
        form = CommentaireForm(request.POST)
        if form.is_valid():
            Commentaire.objects.create(
                article_id=article,
                auteur_id=request.user,
                contenu=form.cleaned_data["contenu"]
            )
            messages.success(request, "Votre commentaire a été ajouté avec succès !")
            return redirect("blog:article", slug=article.slug)

    return render(request, 'blog-single.html', datas)

@login_required
def commentaire_delete(request, slug, id):

    article = get_object_or_404(Article, slug=slug)
    commentaire = get_object_or_404(Commentaire, id=id, article_id=article)

    commentaire.delete()
    messages.success(request, "Commentaire supprimé avec succès.")

    return redirect("blog:article", slug=article.slug)

@login_required
def commentaire_update(request, slug, id):
    article = get_object_or_404(Article, slug=slug)
    commentaire = get_object_or_404(Commentaire, id=id, article_id=article)
    print(commentaire)

    if request.method == 'POST':
        form_comment = CommentaireForm(request.POST, instance=commentaire)
        if form_comment.is_valid():
            form_comment.save()
            messages.success(request, "Commentaire mis à jour avec succès !")
            return redirect('blog:article', slug=article.slug)  # Redirection vers l'article mis à jour
        else:
            messages.error(request, "Veuillez corriger les erreurs dans le formulaire.")

    else:
        form_comment = CommentaireForm(instance=commentaire)  # Pré-remplir le formulaire avec les données existantes

    return render(request, 'blog-single.html', {
        'form_comment': form_comment,
        'article': article,
        'commentaire': commentaire
    })

def tag_page(request,tag):

    articles = Article.objects.filter(tag=tag)

    paginator = Paginator(articles, 6) 
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)

    datas = {
        "articles" : articles,
        "page_obj": page_obj
    }

    return render()

blog/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	<!-- Meta -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="Awaiken">
    {% block title %}
    	<!-- Page Title -->
        <title>Inspaire - Architecture and Interior Design HTML Template</title>
        <!-- Favicon Icon -->
    {% endblock title %}
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}">
	<!-- Google Fonts Css-->
	<link rel="preconnect" href="https://fonts.googleapis.com/">
    <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:ital,wght@0,100..900;1,100..900&amp;display=swap" rel="stylesheet">
	<!-- Bootstrap Css -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
	<!-- SlickNav Css -->
	<link href="{% static 'css/slicknav.min.css' %}" rel="stylesheet">
	<!-- Swiper Css -->
	<link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
	<!-- Font Awesome Icon Css-->
	<link href="{% static 'css/all.min.css' %}" rel="stylesheet" media="screen">
	<!-- Animated Css -->
	<link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <!-- Magnific Popup Core Css File -->
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<!-- Mouse Cursor Css File -->
	<link rel="stylesheet" href="{% static 'css/mousecursor.css' %}">
	<!-- Main Custom Css -->
	<link href="{% static 'css/custom.css' %}" rel="stylesheet" media="screen">
</head>
<body>

    <!-- Preloader Start -->
	<div class="preloader">
		<div class="loading-container">
			<div class="loading"></div>
			<div id="loading-icon"><img src="{% static 'images/loader.svg' %}" alt=""></div>
		</div>
	</div>
	<!-- Preloader End -->

    <!-- Header Start -->
	<header class="main-header">
		<div class="header-sticky">
			<nav class="container">
				<div class="navbar navbar-expand-lg">
					<!-- Logo Start -->
					<a class="navbar-brand" href="{% url 'blog:index' %}">
						<img src="{% static 'images/logo.svg' %}" alt="Logo">
					</a>
					<!-- Logo End -->

					<!-- Main Menu Start -->
					<div class="collapse navbar-collapse main-menu">
                        <div class="nav-menu-wrapper">
                            <ul class="navbar-nav mr-auto" id="menu">
                                <li class="nav-item"><a class="nav-link" href="{% url 'blog:index' %}">Home</a></li>                                                               
                                <li class="nav-item"><a class="nav-link" href="{% url 'blog:about' %}">About Us</a>
                                <li class="nav-item"><a class="nav-link" href="{% url 'blog:blog' %}">Blog</a></li> 
                                <li class="nav-item"><a class="nav-link" href="{% url 'blog:contact' %}">Contact Us</a></li>  
                                <li class="nav-item">                          
                                {% if request.user.is_authenticated %}
                                    <a href="{% url 'blog:board' %}" class="nav-link">Ajouter un article</article></a>
                                {% else %}
                                    <a href="{% url 'Authentification:login' %}" class="nav-link">Se connecter</a>
                                {% endif %}
                                </li>                           
                            </ul>
                        </div>
                        <!-- Header Btn Start -->
                        <div class="header-btn d-inline-flex">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'Authentification:logout' %}" class="btn-default">Se deconnecter</a>
                            {% else %}
                                <a href="{% url 'Authentification:login' %}" class="btn-default">Se connecter</a>
                            {% endif %}
                        
                        </div>
                        <!-- Header Btn End -->
					</div>
					<!-- Main Menu End -->
					<div class="navbar-toggle"></div>
				</div>
			</nav>
			<div class="responsive-menu"></div>
		</div>
	</header>
	<!-- Header End -->
    {% block content %}
    {% endblock %}

    <!-- Jquery Library File -->
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <!-- Bootstrap js file -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- Validator js file -->
    <script src="{% static 'js/validator.min.js' %}"></script>
    <!-- SlickNav js file -->
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <!-- Swiper js file -->
    <script src="{% static 'js/swiper-bundle.min.js' %}"></script>
    <!-- Counter js file -->
    <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <!-- Isotop js file -->
	<script src="{% static 'js/isotope.min.js' %}"></script>
    <!-- Magnific js file -->
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <!-- SmoothScroll -->
    <script src="{% static 'js/SmoothScroll.js' %}"></script>
    <!-- Parallax js -->
    <script src="{% static 'js/parallaxie.js' %}"></script>
    <!-- MagicCursor js file -->
    <script src="{% static 'js/gsap.min.js' %}"></script>
    <script src="{% static 'js/magiccursor.js' %}"></script>
    <!-- Text Effect js file -->
    <script src="{% static 'js/SplitText.js' %}"></script>
    <script src="{% static 'js/ScrollTrigger.min.js' %}"></script>
    <!-- YTPlayer js File -->
    <script src="{% static 'js/jquery.mb.YTPlayer.min.js' %}"></script>
    <!-- Wow js file -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <!-- Main Custom js file -->
    <script src="{% static 'js/function.js' %}"></script>


</body>

blog/templates/base/dashboardbase.html
{% load static %}
{{ form_contenu.media }}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter un article</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
</head>
<body class="bg-light">

    <!-- Header -->
    <nav class="navbar navbar-dark bg-dark px-3">
        <a class="navbar-brand" href="{% url 'blog:index' %}">
            <img src="{% static 'images/logo.svg' %}" alt="Logo">
        </a>
        <a href="{% url 'Authentification:logout' %}" class="btn btn-danger">Se Déconnecter</a>
    </nav>

    {% block content %}
    {% endblock %}

    <!-- Jquery Library File -->
    <script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>
    <!-- Bootstrap js file -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>